reviewers:
  defaults:
    - repository-owners

  groups:
    repository-owners:
      - mamtaharris
    core-contributors:
      - RejinR
      - mamtaharris
    other-contributors:
      - RejinR
      
files:
  '**':
    - repository-owners
  '**/*.go':
    - core-contributors
  '**/*.yml':
    - other-contributors
