name: 'Auto Author Assign'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.4.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            config: .github/auto-author-assign.yml 
